import Head from "next/head";
import { withTranslation } from "../i18n";

import styles from "../styles/Home.module.css";

const Home = ({ t }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJs Translate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{t("common:title")}</h1>
        <h2 className={styles.salutation}>{t("common:salutation")}</h2>
      </main>
    </div>
  );
};

export default withTranslation()(Home);
