import Head from "next/head";
import { useTranslation } from "next-i18next";

import styles from "../styles/Home.module.css";

export default function Home() {
  const { t } = useTranslation("common");

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJs Translate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.salutation}>{t("title")}</h1>
      </main>
    </div>
  );
}
